### ISSUE TITLE
[TODO 페이지] 일주일 단위 날짜 선택

### ISSUE THREAD

**Issue by jayjeong8** [EasyAndBeauty/DailyReceipt-Flutter#12]
### 배경

매일매일 todo를 기록해서 데일리 영수증으로 만들 수 있도록 날짜 선택 기능을 제공합니다.

### 작업할 내용
- 일주일 단위로 나타나는 날짜 선택 UI 구현
<img width="342" alt="image" src="https://github.com/EasyAndBeauty/DailyReceipt-Flutter/assets/82160479/c7a3ed66-759d-44cb-8d7a-388b173e5466">

#### 날짜 구간 이동
기존에는 다른 일주일 구간을 보고싶다면 캘린더를 이용해서 다른 날짜로 이동해야 했습니다.
대신 날짜 목록 위에서 왼쪽이나 오른쪽으로 손가락을 슬라이딩하면 이전 일주일이나 다음 일주일을 볼 수 있으면 좋겠습니다!
다만 사용자가 투두 기록이 쌓일 수록 이전 기록을 탐색하고 싶은 니즈가 많을지에 대해 고민이 먼저 필요할 것 같습니다.

**Comment by jayjeong8** [comment]
#13 이슈에서 진행된 것과 유사한 방식으로 적용하면 좋을 것 같아요!

사용한 캘린더 패키지에 제가 작업한 월간 달력 외에도 1주일 단위로 날짜를 표시할 수 있고,
슬라이딩 기능이 구현되어 있으며 커스텀 스타일을 적용할 수 있습니다.

그리고 저 이슈에서 작업된 calendar Provider를 이용해서 selectedDate 상태를 저장해주면 될 것 같아요~!

**Comment by IGhost-P** [comment]
이 이슈 작업하시는분 없으시다면 제가 작업해도 될까욥~

**Comment by jayjeong8** [comment]
> 이 이슈 작업하시는분 없으시다면 제가 작업해도 될까욥~

그럼용~
