### ISSUE TITLE
[Feature] ios 개발자를 위한 환경설정 README 작성

### ISSUE THREAD

**Issue by IGhost-P** [EasyAndBeauty/DailyReceipt-Flutter#16]
### 배경

clone을 하고 나서 처음 Flutter를 설치하다 보니 웹개발과 설치하는 방법등이 조금 상이한게 있어서 헷갈렸습니다.. ㅠㅠ
다시는 삽질하지 않게 최대한 쉬운 step으로 README를 작성하려 합니다.

### 작업할 내용

- clone이후 ios lunch 하는 step을 작성

### 추가 내용

없습니다.

**Comment by gygy7151** [comment]
최고..!!!!
