### ISSUE TITLE
[service] 영수증 상세보기 페이지 이미지 저장 기능 구현

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-Flutter#33]
### 배경

이 작업을 왜 해야 하는지에 대해 작성해요. (ex_작업의 목적이나 가치 등)

### 작업할 내용
어떤 작업을 진행해야 하는지 작성해요. (ex_기능의 상세 구현 사항, 고민 중인 문제 해결 방식 등)

### 추가 내용

기능과 관련된 원하는 내용을 자유롭게 작성해요. (ex_스크린샷이나 부가적인 내용 등)

**Comment by IGhost-P** [comment]
작업한다면 공유까지 작업해보겠습니다. 앱이니깐 쉽게 가능할것 같아요
