### ISSUE TITLE
플러터 스터디

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-Flutter#36]

**Comment by IGhost-P** [comment]
저는 현재 UXUI 스터디하면서 플러터로 개발하고 있기는한데..


![Image](https://github.com/user-attachments/assets/75044496-d015-40a1-9fcf-991609b326ab)

관심 있으신분들은 댓글 부탁드립니다~!

**Comment by mdgarden** [comment]
개인적으로 진행하고 있는 스터디인가요?!
