### ISSUE TITLE
[Feature] UI 아이콘 관련 UX 개선

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-Flutter#42]
### 배경

아이콘과 관련된 UI/UX를 개선합니다.

#### 삭제 버튼
기존 이슈 #11 에서도 있었던 논의입니다. 삭제 버튼을 포함한 삭제 방식 자체에 대해서 재의논합니다.

#### 수정 완료 버튼
todo의 수정 내용을 수정시 연필 모양 아이콘이 체크 표시로 바뀝니다. todo 완료 표시와 혼동될 여지가 있어 다른 아이콘으로 변경하는 것이 좋아보입니다.

현재 구현되어있는 todo 항목과 아이콘들
<img width="377" alt="image" src="https://github.com/user-attachments/assets/db73c9d7-92ae-4984-90cc-76dd18db1e75">

기타 아이콘관련해서 개선사항이 있으면 이 이슈에 추가합니다.

**Comment by IGhost-P** [comment]
#58 과 같은 논의라 close 합니다.
