### ISSUE TITLE
기존 서버 리포지토리 배포 방법 및 DB 검토

### ISSUE THREAD

**Issue by IGhost-P** [EasyAndBeauty/DailyReceipt-Flutter#80]

**Comment by mdgarden** [comment]
## 내용
파이어베이스의 유저인증 및 SNS 로그인 기능을 도입합니다.

## 상세
### 파이어베이스 도입 이유
- 간단하게 SNS로그인을 도입하고, 유저의 정보를 관리할 수 있습니다.
- 파이어베이스의 자체적인 유저 아이디로 유저를 관리할 수 있습니다.

### 도입 내용
- 2차 스프린트에서는 로그인과 유저 정보 저장까지만 관리합니다.
- 파이어 스토어를 활용한 DB저장 방법 및 저장 내용에 대해서는 3차 스프린트에서 재의논합니다.

**Comment by IGhost-P** [comment]
> 요건 우의 의견 확인하고 진행하겠습니다~ 아마 서버 코드 그대로 들고 재배포만해도 동작은 할 것 같아요

그렇다면, 이전과 마찬가지로 docker로 서버를 띄우고 작업을 진행하면 될까요?

**Comment by mdgarden** [comment]
환경변수만 확인하면 로컬은 도커로 돌려도 문제 없을 것 같습니다! 배포 방법은 제가 좀 더 생각해볼게요~
