### ISSUE TITLE
서버/DB 배포

### ISSUE THREAD

**Issue by IGhost-P** [EasyAndBeauty/DailyReceipt-Flutter#81]

**Comment by mdgarden** [comment]
내년 5월까지 AWS 무료인 계정이 있어서 거기에 서버/DB 배포하겠습니다~
사양 자체는 특별히 고민하지 않고 기존 사양 그대로 갈 예정입니다.
기타 수정이 필요한 곳

- 각종 환경변수
- 카카오 로그인/auth 관련 개발자 키
- 필요 API 및 사양 재확인
