### ISSUE TITLE
@1.0.0 수정 사항 우선순위 결정 후 작업

### ISSUE THREAD

**Issue by IGhost-P** [EasyAndBeauty/DailyReceipt-Flutter#88]

**Comment by jayjeong8** [comment]
## 1.0.0 수정 사항

### 타이머
- 백그라운드 상태로 오래 있으면 앱 꺼지는 문제 해결
- 시간을 직접 입력할 수 있는 기능
- 타이머 sheet를 끌어당겼는데 닫히지 않는 문제 해결 (발생 원인 확인 필요)
- 일시 정지 상태에서 타이머를 끄면 기록이 안되는 문제 해결


### 투두
- todo 인풋과 플러스 버튼 UX 개선
- todo 수정 삭제 UX 개선
  - 눌렀을 때 수정으로 변경하고 수정 모드일 때 삭제 아이콘 보이도록.  수정 모드 아닐 때 타이머 아이콘 보이도록.
  - 텍스트 인풋 UI 심미성 개선
  - 인풋 최대 글자 수 지정
    - 무지막지하게 길게 쓰면 타이머 페이지에서 타이머가 밀려서 가려짐 
- 앱을 킬 때 마다 투두 정렬 순서가 변경되는 문제 해결


### 영수증
- 영수증 두줄까지 나오도록 개선 (두줄 나와도 영수증 심미성 괜찮아 보이는지 확인 필요) 
- 안드로이드에서 복붙이 안되는 문제
- 안드로이드에서 저장이 안되는 문제
- 복사 => 완료 스낵바가 깜빡이는 것 처럼 보이는 문제 
  - 복사 중일 때는 버튼 로딩으로 대체하면 좋을 듯
- 영수증 주소에 접근 가능하도록 개선
- 바코드 화질 개선

### 위젯 (후순위, 아이디어만 적음)
- todo 목록과 타이머 버튼이 있는 위젯
- 영수증 미리보기 위젯


### 기타
- 프랑스어 지원..?
