### ISSUE TITLE
[TODO 페이지] todo 목록

### ISSUE THREAD

**Issue by jayjeong8** [EasyAndBeauty/DailyReceipt-Flutter#9]
### 배경

주요 기능인 TODO를 구현하기 위한 작업입니다. 
todo CRUD 중 read를 작업합니다.

### 작업할 내용
todo 목록
- 체크박스나 edit 아이콘 없이 텍스트만 나타나도록 구현합니다. 

### 추가 내용

- text theme 중 bodyMedium을 사용합니다.
- color theme 중 onBackground를 사용합니다.

**Comment by jayjeong8** [comment]
@mdgarden #13 이슈에서 TODO model에 scheduledDate가 추가되었습니다. 

사용자가 todo를 생성할 때 날짜 UI(주간이나 월간)에서 선택한 날짜인 selectedDate를 기준으로 todo의 scheduledDate가 정해집니다!

todo 항목 중 selectedDate와 동일한 scheduledDate를 가진 항목만 보여주면 될 것 같아요! 
작업하시면서 제가 작업한 코드에 궁금한 내용 있으면 알려주세요~!

**Comment by mdgarden** [comment]
질문을 어디다가 적어야할지 모르겠어서 일단 여기에 남겨요!

제 환경에서 시뮬레이터를 실행시키면 이렇게 파일들이 많이 생기는데, 제 환경이라서 그런건가요? 
특별히 다른 설정을 해줘야하는건지, 아니면 원래 이런건지(?) 궁금합니다...!

<img width="298" alt="image" src="https://github.com/EasyAndBeauty/DailyReceipt-Flutter/assets/66259746/fd38459f-c311-4e43-806f-2a9575829f4b">

**Comment by jayjeong8** [comment]
> 제 환경에서 시뮬레이터를 실행시키면 이렇게 파일들이 많이 생기는데, 제 환경이라서 그런건가요? 특별히 다른 설정을 해줘야하는건지, 아니면 원래 이런건지(?) 궁금합니다...!

엇 저는 아래 이미지 정도 새로 생겼던 것 같아요!  

<img width="267" alt="image" src="https://github.com/EasyAndBeauty/DailyReceipt-Flutter/assets/82160479/d8130bf3-c841-4a1d-9898-a7386c9b0434">

**Comment by mdgarden** [comment]
제이도 파일들이 새로 생겼는데 이 리포지토리에 최초로 푸쉬할 때 이미 커밋에 넣으셨다는 뜻인가요?  현재 제이의 환경에서는 작업후 dart파일들과 `pubspec.lock`, `pubspec.yaml`이 두가지 파일만 git 변경사항이 있다는 뜻이 맞을까요?

---
## 현재 의문
- 이미지로 올렸던, 마당의 환경에서 시뮬레이터를 실행하면서 생긴 파일들을 Git으로 관리해야하는가?
- 제이의 환경에서 새로 생긴 파일들과 마당의 환경에서 생긴 파일들의 차이는?
- 댄은 프로젝트를 실행시키면서 새로 파일들이 생기지 않았는지?

## 시도해본 것
- 댄이 톡방에서 알려준 공식 문서의 `.gitignore`의 파일을 적용 
    - 적용해보았으나, 깃 변경사항에서 제외된 파일이 없었습니다. .gitignore 파일의 문제는 아닌듯합니다.

## 검색해본 것
- 챗GPT의 의견(😂)
    - .xconfig, Podfile, .pbxproj 파일들은 프로젝트 설정과 의존성 관리에 중요하므로, 일반적으로 이러한 파일들을 Git을 통해 버전 관리하는 것이 좋습니다. 그러나 .pbxproj 파일의 경우, 팀 내에서 충돌을 관리하는 데 있어 주의를 기울여야 합니다.
- [제가 이미지로 올린 파일들도 관리되어야 한다는 글(레딧)](https://www.reddit.com/r/FlutterDev/comments/d6rwhw/flutter_gitignore_for_team_project/)

## 제안
결과적으로는 제가 이미지로 올린 파일들을 전부 커밋하는게 맞는 것 같은데, 빌드 관련 파일들이 많은 것 같아 무서워져서(?) 다른 분들 의견 듣고 커밋하고 풀리퀘스트 작성하고 싶습니다.ㅠㅠ

**Comment by jayjeong8** [comment]
최초로 푸시할 때는 생성된 파일을 전부 커밋해서 제가 위에 올린 이미지 내의 파일들을 반영했었습니다!  
그 이후로는 해당 파일들에 계속 변경사항이 생기는데 커밋하지 않아도 되는 파일이라고 생각해서 반영하지 않았었어요!

아마 각자 환경이(IDE, mac, window, 설치 방법 등) 달라서 다른 파일들이 생기는 것 같아요.
예를 들면 저는 CocoaPods를 사용하지 않아서 pod 관련 파일이 생기지 않는다던지요!

그래서 시뮬레이터를 돌려서 나온 파일들은 커밋하지 않고 .dart 및 pubspec 파일만 커밋하면 좋을 것 같습니다!!

추가로 저도 chatGPT에 물어본 내용 함께 첨부합니다 :bow:

<img width="616" alt="image" src="https://github.com/EasyAndBeauty/DailyReceipt-Flutter/assets/82160479/698015a2-ebc4-4c74-900a-1710dcb363aa">


--  

위 답변과 무관하게 저희가 사이드 프로젝트를 통해서 조금 더 마음 편하게 일단 부딪혀보고 나서 문제를 해결해보는 경험(?)을 해볼 수도 있다고 생각하고, 그 과정에서 배우는게 있을 수도 있다고 생각해요!!  
만약 나온 파일들을 커밋하는게 맞다고 생각하시면 별도 커밋으로 분리해서 커밋 후에 '어 이거 아니네!' 하면 revert해도 좋습니다😊
